---
# Week 01 Student Container Submissions
#
# Each student adds their entry below after pushing their container to GHCR.
# See README.md for submission instructions.

apiVersion: container-course.ziyotek.edu/v1
kind: StudentSubmissions
metadata:
  week: 1
  semester: spring-2026
  namespace: container-course-week01

students:
  # Example entry - remove this and add your own:
  # - name: "John Doe"
  #   github_username: "johndoe"
  #   container_image: "ghcr.io/johndoe/container-course-student:latest"
  #   student_endpoint: "/student"
  #   health_endpoint: "/health"
  #   port: 5000

  - name: "Jared Gore"
    github_username: "jlgore"
    container_image: "ghcr.io/jlgore/container-course-student:latest"
    student_endpoint: "/student"
    health_endpoint: "/health"

  - name: "zia ahmadi"
    github_username: "zahmadi57"
    container_image: "ghcr.io/zahmadi57/container-course-student:v3-student"
    student_endpoint: "/student"
    health_endpoint: "/health"

  # Add your submission below this line:
# Test trigger 1770313044
# Final test 1770313541
# Test with labels 1770313875
# Final test 1770314436
# Test with scale set name 1770314730
# Test final workflow 1770315026
# Test with curl 1770315075
# Test with permissions fix
